name: Update master1

on:
  workflow_dispatch:
  
  schedule:
    - cron: 0 23 * * *

env: 
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  SCKEY: ${{ secrets.SCKEY }}
  PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  FANQIANG: PASSPULS
  DIY_SH: master1
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: Ubuntu-20.04

    name: Update ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [master1]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git subversion git-core wget curl grep
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Clone packages
      env: 
        GITH: ${{ env.DIY_SH }}
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ${{ env.DIY_SH }}.sh && chmod +x token.sh
        rm -fr ${{matrix.target}} && git clone -b ${{matrix.target}} https://github.com/makebl/OpenClash.git ${{matrix.target}}
        cd ${{matrix.target}}
        rm -Rf *
        git rm --cache *
        $GITHUB_WORKSPACE/${{ env.DIY_SH }}.sh
        $GITHUB_WORKSPACE/token.sh
        [ -f $GITHUB_WORKSPACE/Version_Tags ] && echo "FOLDERPS=1" >> $GITHUB_ENV
        echo "OpenClash" > README.md
        
    - name: Upload
      continue-on-error: true
      run: |
        cd $GITHUB_WORKSPACE
        chmod -R 775 $GITHUB_WORKSPACE/${{matrix.target}}
        [ -e $GITHUB_WORKSPACE/README/LICENSE ] && cp $GITHUB_WORKSPACE/README/LICENSE $GITHUB_WORKSPACE/${{matrix.target}}
        [ -e $GITHUB_WORKSPACE/README/${{ env.DIY_SH }}/README.md ] && cp $GITHUB_WORKSPACE/README/${{ env.DIY_SH }}/README.md $GITHUB_WORKSPACE/${{matrix.target}}
        cd $GITHUB_WORKSPACE/${{matrix.target}}
        if [[ ! "${FOLDERPS}" == "1" ]]; then
          git add .
          git commit -m "同步源码于$(TZ='Asia/Shanghai' date +%Y年%m月%d号-%H点%M分)" || true
          git push --quiet "https://${{ secrets.REPO_TOKEN }}@github.com/makebl/OpenClash.git" HEAD:${{matrix.target}}
        else
          echo "缺少文件，放弃同步..."
        fi
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
        repository: ${{ github.repository }}       
        retain_days: 0.1
        keep_minimum_runs: 0
