name: Clone Repository

on:
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: swaggyP36000/TrollStore-IPAs
